/**
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package se.kth.integral.azure.opinsights.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.microsoft.rest.serializer.JsonFlatten;

/**
 * Value object for saved search results.
 */
@JsonFlatten
public class SavedSearch {
    /**
     * The id of the saved search.
     */
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private String id;

    /**
     * The etag of the saved search.
     */
    private String etag;

    /**
     * The category of the saved search. This helps the user to find a saved
     * search faster.
     */
    @JsonProperty(value = "properties.Category", required = true)
    private String category;

    /**
     * Saved search display name.
     */
    @JsonProperty(value = "properties.DisplayName", required = true)
    private String displayName;

    /**
     * The query expression for the saved search. Please see
     * https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-search-reference
     * for reference.
     */
    @JsonProperty(value = "properties.Query", required = true)
    private String query;

    /**
     * The version number of the query lanuage. Only verion 1 is allowed here.
     */
    @JsonProperty(value = "properties.Version", required = true)
    private long version;

    /**
     * The tags attached to the saved search.
     */
    @JsonProperty(value = "properties.Tags")
    private List<Tag> tags;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Get the etag value.
     *
     * @return the etag value
     */
    public String etag() {
        return this.etag;
    }

    /**
     * Set the etag value.
     *
     * @param etag the etag value to set
     * @return the SavedSearch object itself.
     */
    public SavedSearch withEtag(String etag) {
        this.etag = etag;
        return this;
    }

    /**
     * Get the category value.
     *
     * @return the category value
     */
    public String category() {
        return this.category;
    }

    /**
     * Set the category value.
     *
     * @param category the category value to set
     * @return the SavedSearch object itself.
     */
    public SavedSearch withCategory(String category) {
        this.category = category;
        return this;
    }

    /**
     * Get the displayName value.
     *
     * @return the displayName value
     */
    public String displayName() {
        return this.displayName;
    }

    /**
     * Set the displayName value.
     *
     * @param displayName the displayName value to set
     * @return the SavedSearch object itself.
     */
    public SavedSearch withDisplayName(String displayName) {
        this.displayName = displayName;
        return this;
    }

    /**
     * Get the query value.
     *
     * @return the query value
     */
    public String query() {
        return this.query;
    }

    /**
     * Set the query value.
     *
     * @param query the query value to set
     * @return the SavedSearch object itself.
     */
    public SavedSearch withQuery(String query) {
        this.query = query;
        return this;
    }

    /**
     * Get the version value.
     *
     * @return the version value
     */
    public long version() {
        return this.version;
    }

    /**
     * Set the version value.
     *
     * @param version the version value to set
     * @return the SavedSearch object itself.
     */
    public SavedSearch withVersion(long version) {
        this.version = version;
        return this;
    }

    /**
     * Get the tags value.
     *
     * @return the tags value
     */
    public List<Tag> tags() {
        return this.tags;
    }

    /**
     * Set the tags value.
     *
     * @param tags the tags value to set
     * @return the SavedSearch object itself.
     */
    public SavedSearch withTags(List<Tag> tags) {
        this.tags = tags;
        return this;
    }

}
