/**
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package se.kth.integral.azure.opinsights.models;


/**
 * Schema metadata for search.
 */
public class SearchMetadataSchema {
    /**
     * The name of the metadata schema.
     */
    private String name;

    /**
     * The version of the metadata schema.
     */
    private Integer version;

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the SearchMetadataSchema object itself.
     */
    public SearchMetadataSchema withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the version value.
     *
     * @return the version value
     */
    public Integer version() {
        return this.version;
    }

    /**
     * Set the version value.
     *
     * @param version the version value to set
     * @return the SearchMetadataSchema object itself.
     */
    public SearchMetadataSchema withVersion(Integer version) {
        this.version = version;
        return this;
    }

}
