/**
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package se.kth.integral.azure.opinsights.models;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines values for StorageInsightState.
 */
public final class StorageInsightState {
    /** Static value OK for StorageInsightState. */
    public static final StorageInsightState OK = new StorageInsightState("OK");

    /** Static value ERROR for StorageInsightState. */
    public static final StorageInsightState ERROR = new StorageInsightState("ERROR");

    private String value;

    /**
     * Creates a custom value for StorageInsightState.
     * @param value the custom value
     */
    public StorageInsightState(String value) {
        this.value = value;
    }

    @JsonValue
    @Override
    public String toString() {
        return value;
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof StorageInsightState)) {
            return false;
        }
        if (obj == this) {
            return true;
        }
        StorageInsightState rhs = (StorageInsightState) obj;
        if (value == null) {
            return rhs.value == null;
        } else {
            return value.equals(rhs.value);
        }
    }
}
