/**
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package se.kth.integral.azure.opinsights.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The status of the storage insight.
 */
public class StorageInsightStatus {
    /**
     * The state of the storage insight connection to the workspace. Possible
     * values include: 'OK', 'ERROR'.
     */
    @JsonProperty(required = true)
    private StorageInsightState state;

    /**
     * Description of the state of the storage insight.
     */
    private String description;

    /**
     * Get the state value.
     *
     * @return the state value
     */
    public StorageInsightState state() {
        return this.state;
    }

    /**
     * Set the state value.
     *
     * @param state the state value to set
     * @return the StorageInsightStatus object itself.
     */
    public StorageInsightStatus withState(StorageInsightState state) {
        this.state = state;
        return this;
    }

    /**
     * Get the description value.
     *
     * @return the description value
     */
    public String description() {
        return this.description;
    }

    /**
     * Set the description value.
     *
     * @param description the description value to set
     * @return the StorageInsightStatus object itself.
     */
    public StorageInsightStatus withDescription(String description) {
        this.description = description;
        return this;
    }

}
