/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package se.kth.integral.oms;

import com.microsoft.rest.RestClient;

/**
 * The interface for AzureLogAnalyticspublicAPI class.
 */
public interface AzureLogAnalyticspublicAPI {
    /**
     * Gets the REST client.
     *
     * @return the {@link RestClient} object.
    */
    RestClient restClient();

    /**
     * The default base URL.
     */
    String DEFAULT_BASE_URL = "https://api.loganalytics.io/v1";

    /**
     * Gets ID of the workspace. This is Workspace ID from the Properties blade in the Azure portal..
     *
     * @return the workspaceId value.
     */
    String workspaceId();

    /**
     * Sets ID of the workspace. This is Workspace ID from the Properties blade in the Azure portal..
     *
     * @param workspaceId the workspaceId value.
     * @return the service client itself
     */
    AzureLogAnalyticspublicAPI withWorkspaceId(String workspaceId);

    /**
     * Gets the Querys object to access its operations.
     * @return the Querys object.
     */
    Querys querys();

}
