/**
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package se.kth.integral.azure.opinsights;

import com.microsoft.rest.ServiceCall;
import com.microsoft.rest.ServiceCallback;
import com.microsoft.rest.ServiceResponse;
import rx.Observable;
import se.kth.integral.azure.opinsights.models.SavedSearch;
import se.kth.integral.azure.opinsights.models.SavedSearchesListResult;
import se.kth.integral.azure.opinsights.models.SearchResultsResponse;

/**
 * An instance of this class provides access to all the operations defined
 * in SavedSearches.
 */
public interface SavedSearches {
    /**
     * Deletes the specified saved search in a given workspace.
     *
     * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
     * @param workspaceName Log Analytics workspace name
     * @param savedSearchName Name of the saved search.
     */
    void delete(String resourceGroupName, String workspaceName, String savedSearchName);

    /**
     * Deletes the specified saved search in a given workspace.
     *
     * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
     * @param workspaceName Log Analytics workspace name
     * @param savedSearchName Name of the saved search.
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @return the {@link ServiceCall} object
     */
    ServiceCall<Void> deleteAsync(String resourceGroupName, String workspaceName, String savedSearchName, final ServiceCallback<Void> serviceCallback);

    /**
     * Deletes the specified saved search in a given workspace.
     *
     * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
     * @param workspaceName Log Analytics workspace name
     * @param savedSearchName Name of the saved search.
     * @return the {@link ServiceResponse} object if successful.
     */
    Observable<Void> deleteAsync(String resourceGroupName, String workspaceName, String savedSearchName);

    /**
     * Deletes the specified saved search in a given workspace.
     *
     * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
     * @param workspaceName Log Analytics workspace name
     * @param savedSearchName Name of the saved search.
     * @return the {@link ServiceResponse} object if successful.
     */
    Observable<ServiceResponse<Void>> deleteWithServiceResponseAsync(String resourceGroupName, String workspaceName, String savedSearchName);

    /**
     * Creates or updates a saved search for a given workspace.
     *
     * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
     * @param workspaceName Log Analytics workspace name
     * @param savedSearchName The id of the saved search.
     * @param parameters The parameters required to save a search.
     * @return the SavedSearch object if successful.
     */
    SavedSearch createOrUpdate(String resourceGroupName, String workspaceName, String savedSearchName, SavedSearch parameters);

    /**
     * Creates or updates a saved search for a given workspace.
     *
     * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
     * @param workspaceName Log Analytics workspace name
     * @param savedSearchName The id of the saved search.
     * @param parameters The parameters required to save a search.
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @return the {@link ServiceCall} object
     */
    ServiceCall<SavedSearch> createOrUpdateAsync(String resourceGroupName, String workspaceName, String savedSearchName, SavedSearch parameters, final ServiceCallback<SavedSearch> serviceCallback);

    /**
     * Creates or updates a saved search for a given workspace.
     *
     * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
     * @param workspaceName Log Analytics workspace name
     * @param savedSearchName The id of the saved search.
     * @param parameters The parameters required to save a search.
     * @return the observable to the SavedSearch object
     */
    Observable<SavedSearch> createOrUpdateAsync(String resourceGroupName, String workspaceName, String savedSearchName, SavedSearch parameters);

    /**
     * Creates or updates a saved search for a given workspace.
     *
     * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
     * @param workspaceName Log Analytics workspace name
     * @param savedSearchName The id of the saved search.
     * @param parameters The parameters required to save a search.
     * @return the observable to the SavedSearch object
     */
    Observable<ServiceResponse<SavedSearch>> createOrUpdateWithServiceResponseAsync(String resourceGroupName, String workspaceName, String savedSearchName, SavedSearch parameters);

    /**
     * Gets the specified saved search for a given workspace.
     *
     * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
     * @param workspaceName Log Analytics workspace name
     * @param savedSearchName The id of the saved search.
     * @return the SavedSearch object if successful.
     */
    SavedSearch get(String resourceGroupName, String workspaceName, String savedSearchName);

    /**
     * Gets the specified saved search for a given workspace.
     *
     * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
     * @param workspaceName Log Analytics workspace name
     * @param savedSearchName The id of the saved search.
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @return the {@link ServiceCall} object
     */
    ServiceCall<SavedSearch> getAsync(String resourceGroupName, String workspaceName, String savedSearchName, final ServiceCallback<SavedSearch> serviceCallback);

    /**
     * Gets the specified saved search for a given workspace.
     *
     * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
     * @param workspaceName Log Analytics workspace name
     * @param savedSearchName The id of the saved search.
     * @return the observable to the SavedSearch object
     */
    Observable<SavedSearch> getAsync(String resourceGroupName, String workspaceName, String savedSearchName);

    /**
     * Gets the specified saved search for a given workspace.
     *
     * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
     * @param workspaceName Log Analytics workspace name
     * @param savedSearchName The id of the saved search.
     * @return the observable to the SavedSearch object
     */
    Observable<ServiceResponse<SavedSearch>> getWithServiceResponseAsync(String resourceGroupName, String workspaceName, String savedSearchName);

    /**
     * Gets the saved searches for a given Log Analytics Workspace.
     *
     * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
     * @param workspaceName Log Analytics workspace name
     * @return the SavedSearchesListResult object if successful.
     */
    SavedSearchesListResult listByWorkspace(String resourceGroupName, String workspaceName);

    /**
     * Gets the saved searches for a given Log Analytics Workspace.
     *
     * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
     * @param workspaceName Log Analytics workspace name
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @return the {@link ServiceCall} object
     */
    ServiceCall<SavedSearchesListResult> listByWorkspaceAsync(String resourceGroupName, String workspaceName, final ServiceCallback<SavedSearchesListResult> serviceCallback);

    /**
     * Gets the saved searches for a given Log Analytics Workspace.
     *
     * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
     * @param workspaceName Log Analytics workspace name
     * @return the observable to the SavedSearchesListResult object
     */
    Observable<SavedSearchesListResult> listByWorkspaceAsync(String resourceGroupName, String workspaceName);

    /**
     * Gets the saved searches for a given Log Analytics Workspace.
     *
     * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
     * @param workspaceName Log Analytics workspace name
     * @return the observable to the SavedSearchesListResult object
     */
    Observable<ServiceResponse<SavedSearchesListResult>> listByWorkspaceWithServiceResponseAsync(String resourceGroupName, String workspaceName);

    /**
     * Gets the results from a saved search for a given workspace.
     *
     * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
     * @param workspaceName Log Analytics workspace name
     * @param savedSearchName The name of the saved search.
     * @return the SearchResultsResponse object if successful.
     */
    SearchResultsResponse getResults(String resourceGroupName, String workspaceName, String savedSearchName);

    /**
     * Gets the results from a saved search for a given workspace.
     *
     * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
     * @param workspaceName Log Analytics workspace name
     * @param savedSearchName The name of the saved search.
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @return the {@link ServiceCall} object
     */
    ServiceCall<SearchResultsResponse> getResultsAsync(String resourceGroupName, String workspaceName, String savedSearchName, final ServiceCallback<SearchResultsResponse> serviceCallback);

    /**
     * Gets the results from a saved search for a given workspace.
     *
     * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
     * @param workspaceName Log Analytics workspace name
     * @param savedSearchName The name of the saved search.
     * @return the observable to the SearchResultsResponse object
     */
    Observable<SearchResultsResponse> getResultsAsync(String resourceGroupName, String workspaceName, String savedSearchName);

    /**
     * Gets the results from a saved search for a given workspace.
     *
     * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
     * @param workspaceName Log Analytics workspace name
     * @param savedSearchName The name of the saved search.
     * @return the observable to the SearchResultsResponse object
     */
    Observable<ServiceResponse<SearchResultsResponse>> getResultsWithServiceResponseAsync(String resourceGroupName, String workspaceName, String savedSearchName);

}
