/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package se.kth.integral.oms.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Error details.
 */
public class ErrorDetail {
    /**
     * The error's code.
     */
    @JsonProperty(value = "code", required = true)
    private String code;

    /**
     * A human readable error message.
     */
    @JsonProperty(value = "message", required = true)
    private String message;

    /**
     * Indicates which property in the request is responsible for the error.
     */
    @JsonProperty(value = "target")
    private String target;

    /**
     * Indicates which value in 'target' is responsible for the error.
     */
    @JsonProperty(value = "value")
    private String value;

    /**
     * Indicates resources which were responsible for the error.
     */
    @JsonProperty(value = "resources")
    private List<String> resources;

    /**
     * The additionalProperties property.
     */
    @JsonProperty(value = "additionalProperties")
    private Object additionalProperties;

    /**
     * Get the code value.
     *
     * @return the code value
     */
    public String code() {
        return this.code;
    }

    /**
     * Set the code value.
     *
     * @param code the code value to set
     * @return the ErrorDetail object itself.
     */
    public ErrorDetail withCode(String code) {
        this.code = code;
        return this;
    }

    /**
     * Get the message value.
     *
     * @return the message value
     */
    public String message() {
        return this.message;
    }

    /**
     * Set the message value.
     *
     * @param message the message value to set
     * @return the ErrorDetail object itself.
     */
    public ErrorDetail withMessage(String message) {
        this.message = message;
        return this;
    }

    /**
     * Get the target value.
     *
     * @return the target value
     */
    public String target() {
        return this.target;
    }

    /**
     * Set the target value.
     *
     * @param target the target value to set
     * @return the ErrorDetail object itself.
     */
    public ErrorDetail withTarget(String target) {
        this.target = target;
        return this;
    }

    /**
     * Get the value value.
     *
     * @return the value value
     */
    public String value() {
        return this.value;
    }

    /**
     * Set the value value.
     *
     * @param value the value value to set
     * @return the ErrorDetail object itself.
     */
    public ErrorDetail withValue(String value) {
        this.value = value;
        return this;
    }

    /**
     * Get the resources value.
     *
     * @return the resources value
     */
    public List<String> resources() {
        return this.resources;
    }

    /**
     * Set the resources value.
     *
     * @param resources the resources value to set
     * @return the ErrorDetail object itself.
     */
    public ErrorDetail withResources(List<String> resources) {
        this.resources = resources;
        return this;
    }

    /**
     * Get the additionalProperties value.
     *
     * @return the additionalProperties value
     */
    public Object additionalProperties() {
        return this.additionalProperties;
    }

    /**
     * Set the additionalProperties value.
     *
     * @param additionalProperties the additionalProperties value to set
     * @return the ErrorDetail object itself.
     */
    public ErrorDetail withAdditionalProperties(Object additionalProperties) {
        this.additionalProperties = additionalProperties;
        return this;
    }

}
