/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package se.kth.integral.oms.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Error details.
 * Contains details when the response code indicates an error.
 */
public class ErrorResponse {
    /**
     * The error details.
     */
    @JsonProperty(value = "error", required = true)
    private ErrorInfo error;

    /**
     * Get the error value.
     *
     * @return the error value
     */
    public ErrorInfo error() {
        return this.error;
    }

    /**
     * Set the error value.
     *
     * @param error the error value to set
     * @return the ErrorResponse object itself.
     */
    public ErrorResponse withError(ErrorInfo error) {
        this.error = error;
        return this;
    }

}
