/**
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package se.kth.integral.oms.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Metadata for a workspace that isn't linked to an Azure subscription.
 */
public class LinkTarget {
    /**
     * The GUID that uniquely identifies the workspace.
     */
    private String customerId;

    /**
     * The display name of the workspace.
     */
    @JsonProperty(value = "accountName")
    private String displayName;

    /**
     * The DNS valid workspace name.
     */
    private String workspaceName;

    /**
     * The location of the workspace.
     */
    private String location;

    /**
     * Get the customerId value.
     *
     * @return the customerId value
     */
    public String customerId() {
        return this.customerId;
    }

    /**
     * Set the customerId value.
     *
     * @param customerId the customerId value to set
     * @return the LinkTarget object itself.
     */
    public LinkTarget withCustomerId(String customerId) {
        this.customerId = customerId;
        return this;
    }

    /**
     * Get the displayName value.
     *
     * @return the displayName value
     */
    public String displayName() {
        return this.displayName;
    }

    /**
     * Set the displayName value.
     *
     * @param displayName the displayName value to set
     * @return the LinkTarget object itself.
     */
    public LinkTarget withDisplayName(String displayName) {
        this.displayName = displayName;
        return this;
    }

    /**
     * Get the workspaceName value.
     *
     * @return the workspaceName value
     */
    public String workspaceName() {
        return this.workspaceName;
    }

    /**
     * Set the workspaceName value.
     *
     * @param workspaceName the workspaceName value to set
     * @return the LinkTarget object itself.
     */
    public LinkTarget withWorkspaceName(String workspaceName) {
        this.workspaceName = workspaceName;
        return this;
    }

    /**
     * Get the location value.
     *
     * @return the location value
     */
    public String location() {
        return this.location;
    }

    /**
     * Set the location value.
     *
     * @param location the location value to set
     * @return the LinkTarget object itself.
     */
    public LinkTarget withLocation(String location) {
        this.location = location;
        return this;
    }

}
