// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

/**
 * This package contains the models classes for AzureLogAnalyticspublicAPI.
 * This API exposes Azure Log Analytics query capabilities.
 */
package se.kth.integral.oms.models;
