// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

/**
 * This package contains the models classes for AzureLogAnalytics.
 * Azure Log Analytics API reference for LinkTargets, StorageInsightConfigs and SavedSearches.
 */
package se.kth.integral.oms.models;
