/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package se.kth.integral.oms.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Analytics query. Learn more about the [Analytics query
 * syntax](https://azure.microsoft.com/documentation/articles/app-insights-analytics-reference/).
 */
public class QueryBody {
    /**
     * The query to execute.
     */
    @JsonProperty(value = "query", required = true)
    private String query;

    /**
     * Optional. The timespan over which to query data. This is an ISO8601 time
     * period value.  This timespan is applied in addition to any that are
     * specified in the query expression.
     */
    @JsonProperty(value = "timespan")
    private String timespan;

    /**
     * something about cross workspace queries.
     */
    @JsonProperty(value = "workspaces")
    private List<String> workspaces;

    /**
     * Get the query value.
     *
     * @return the query value
     */
    public String query() {
        return this.query;
    }

    /**
     * Set the query value.
     *
     * @param query the query value to set
     * @return the QueryBody object itself.
     */
    public QueryBody withQuery(String query) {
        this.query = query;
        return this;
    }

    /**
     * Get the timespan value.
     *
     * @return the timespan value
     */
    public String timespan() {
        return this.timespan;
    }

    /**
     * Set the timespan value.
     *
     * @param timespan the timespan value to set
     * @return the QueryBody object itself.
     */
    public QueryBody withTimespan(String timespan) {
        this.timespan = timespan;
        return this;
    }

    /**
     * Get the workspaces value.
     *
     * @return the workspaces value
     */
    public List<String> workspaces() {
        return this.workspaces;
    }

    /**
     * Set the workspaces value.
     *
     * @param workspaces the workspaces value to set
     * @return the QueryBody object itself.
     */
    public QueryBody withWorkspaces(List<String> workspaces) {
        this.workspaces = workspaces;
        return this;
    }

}
