/**
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package se.kth.integral.oms.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The saved search operation response.
 */
public class SavedSearchesListResult {
    /**
     * The metadata from search results.
     */
    @JsonProperty(value = "__metadata")
    private SearchMetadata metadata;

    /**
     * The array of result values.
     */
    private List<SavedSearch> value;

    /**
     * Get the metadata value.
     *
     * @return the metadata value
     */
    public SearchMetadata metadata() {
        return this.metadata;
    }

    /**
     * Set the metadata value.
     *
     * @param metadata the metadata value to set
     * @return the SavedSearchesListResult object itself.
     */
    public SavedSearchesListResult withMetadata(SearchMetadata metadata) {
        this.metadata = metadata;
        return this;
    }

    /**
     * Get the value value.
     *
     * @return the value value
     */
    public List<SavedSearch> value() {
        return this.value;
    }

    /**
     * Set the value value.
     *
     * @param value the value value to set
     * @return the SavedSearchesListResult object itself.
     */
    public SavedSearchesListResult withValue(List<SavedSearch> value) {
        this.value = value;
        return this;
    }

}
