/**
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package se.kth.integral.oms.models;


/**
 * Highlight details.
 */
public class SearchHighlight {
    /**
     * The string that is put before a matched result.
     */
    private String pre;

    /**
     * The string that is put after a matched result.
     */
    private String post;

    /**
     * Get the pre value.
     *
     * @return the pre value
     */
    public String pre() {
        return this.pre;
    }

    /**
     * Set the pre value.
     *
     * @param pre the pre value to set
     * @return the SearchHighlight object itself.
     */
    public SearchHighlight withPre(String pre) {
        this.pre = pre;
        return this;
    }

    /**
     * Get the post value.
     *
     * @return the post value
     */
    public String post() {
        return this.post;
    }

    /**
     * Set the post value.
     *
     * @param post the post value to set
     * @return the SearchHighlight object itself.
     */
    public SearchHighlight withPost(String post) {
        this.post = post;
        return this;
    }

}
