/**
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package se.kth.integral.oms.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The get search result operation response.
 */
public class SearchResultsResponse {
    /**
     * The id of the search, which includes the full url.
     */
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private String id;

    /**
     * The metadata from search results.
     */
    @JsonProperty(value = "__metadata")
    private SearchMetadata metadata;

    /**
     * The array of result values.
     */
    private List<Object> value;

    /**
     * The error.
     */
    private SearchError error;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Get the metadata value.
     *
     * @return the metadata value
     */
    public SearchMetadata metadata() {
        return this.metadata;
    }

    /**
     * Set the metadata value.
     *
     * @param metadata the metadata value to set
     * @return the SearchResultsResponse object itself.
     */
    public SearchResultsResponse withMetadata(SearchMetadata metadata) {
        this.metadata = metadata;
        return this;
    }

    /**
     * Get the value value.
     *
     * @return the value value
     */
    public List<Object> value() {
        return this.value;
    }

    /**
     * Set the value value.
     *
     * @param value the value value to set
     * @return the SearchResultsResponse object itself.
     */
    public SearchResultsResponse withValue(List<Object> value) {
        this.value = value;
        return this;
    }

    /**
     * Get the error value.
     *
     * @return the error value
     */
    public SearchError error() {
        return this.error;
    }

    /**
     * Set the error value.
     *
     * @param error the error value to set
     * @return the SearchResultsResponse object itself.
     */
    public SearchResultsResponse withError(SearchError error) {
        this.error = error;
        return this;
    }

}
