/**
 * Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package se.kth.integral.oms.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.microsoft.rest.serializer.JsonFlatten;

/**
 * The top level storage insight resource container.
 */
@JsonFlatten
public class StorageInsight extends ProxyResource {
    /**
     * The names of the blob containers that the workspace should read.
     */
    @JsonProperty(value = "properties.containers")
    private List<String> containers;

    /**
     * The names of the Azure tables that the workspace should read.
     */
    @JsonProperty(value = "properties.tables")
    private List<String> tables;

    /**
     * The storage account connection details.
     */
    @JsonProperty(value = "properties.storageAccount", required = true)
    private StorageAccount storageAccount;

    /**
     * The status of the storage insight.
     */
    @JsonProperty(value = "properties.status", access = JsonProperty.Access.WRITE_ONLY)
    private StorageInsightStatus status;

    /**
     * The ETag of the storage insight.
     */
    private String eTag;

    /**
     * Get the containers value.
     *
     * @return the containers value
     */
    public List<String> containers() {
        return this.containers;
    }

    /**
     * Set the containers value.
     *
     * @param containers the containers value to set
     * @return the StorageInsight object itself.
     */
    public StorageInsight withContainers(List<String> containers) {
        this.containers = containers;
        return this;
    }

    /**
     * Get the tables value.
     *
     * @return the tables value
     */
    public List<String> tables() {
        return this.tables;
    }

    /**
     * Set the tables value.
     *
     * @param tables the tables value to set
     * @return the StorageInsight object itself.
     */
    public StorageInsight withTables(List<String> tables) {
        this.tables = tables;
        return this;
    }

    /**
     * Get the storageAccount value.
     *
     * @return the storageAccount value
     */
    public StorageAccount storageAccount() {
        return this.storageAccount;
    }

    /**
     * Set the storageAccount value.
     *
     * @param storageAccount the storageAccount value to set
     * @return the StorageInsight object itself.
     */
    public StorageInsight withStorageAccount(StorageAccount storageAccount) {
        this.storageAccount = storageAccount;
        return this;
    }

    /**
     * Get the status value.
     *
     * @return the status value
     */
    public StorageInsightStatus status() {
        return this.status;
    }

    /**
     * Get the eTag value.
     *
     * @return the eTag value
     */
    public String eTag() {
        return this.eTag;
    }

    /**
     * Set the eTag value.
     *
     * @param eTag the eTag value to set
     * @return the StorageInsight object itself.
     */
    public StorageInsight withETag(String eTag) {
        this.eTag = eTag;
        return this;
    }

}
