/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package se.kth.integral.oms.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The TableObjectColumnsItem model.
 */
public class TableObjectColumnsItem {
    /**
     * The name of this column.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * The data type of this column.
     */
    @JsonProperty(value = "type")
    private String type;

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the TableObjectColumnsItem object itself.
     */
    public TableObjectColumnsItem withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the type value.
     *
     * @return the type value
     */
    public String type() {
        return this.type;
    }

    /**
     * Set the type value.
     *
     * @param type the type value to set
     * @return the TableObjectColumnsItem object itself.
     */
    public TableObjectColumnsItem withType(String type) {
        this.type = type;
        return this;
    }

}
