/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package se.kth.integral.oms.implementation;

import se.kth.integral.oms.AzureLogAnalyticspublicAPI;
import se.kth.integral.oms.Querys;
import com.microsoft.rest.ServiceClient;
import com.microsoft.rest.RestClient;
import okhttp3.OkHttpClient;
import retrofit2.Retrofit;

/**
 * Initializes a new instance of the AzureLogAnalyticspublicAPI class.
 */
public class AzureLogAnalyticspublicAPIImpl extends ServiceClient implements AzureLogAnalyticspublicAPI {

    /** ID of the workspace. This is Workspace ID from the Properties blade in the Azure portal. */
    private String workspaceId;

    /**
     * Gets ID of the workspace. This is Workspace ID from the Properties blade in the Azure portal.
     *
     * @return the workspaceId value.
     */
    public String workspaceId() {
        return this.workspaceId;
    }

    /**
     * Sets ID of the workspace. This is Workspace ID from the Properties blade in the Azure portal.
     *
     * @param workspaceId the workspaceId value.
     * @return the service client itself
     */
    public AzureLogAnalyticspublicAPIImpl withWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId;
        return this;
    }

    /**
     * The Querys object to access its operations.
     */
    private Querys querys;

    /**
     * Gets the Querys object to access its operations.
     * @return the Querys object.
     */
    public Querys querys() {
        return this.querys;
    }

    /**
     * Initializes an instance of AzureLogAnalyticspublicAPI client.
     */
    public AzureLogAnalyticspublicAPIImpl() {
        this("https://api.loganalytics.io/v1");
    }

    /**
     * Initializes an instance of AzureLogAnalyticspublicAPI client.
     *
     * @param baseUrl the base URL of the host
     */
    public AzureLogAnalyticspublicAPIImpl(String baseUrl) {
        super(baseUrl);
        initialize();
    }

    /**
     * Initializes an instance of AzureLogAnalyticspublicAPI client.
     *
     * @param clientBuilder the builder for building an OkHttp client, bundled with user configurations
     * @param restBuilder the builder for building an Retrofit client, bundled with user configurations
     */
    public AzureLogAnalyticspublicAPIImpl(OkHttpClient.Builder clientBuilder, Retrofit.Builder restBuilder) {
        this("https://api.loganalytics.io/v1", clientBuilder, restBuilder);
        initialize();
    }

    /**
     * Initializes an instance of AzureLogAnalyticspublicAPI client.
     *
     * @param baseUrl the base URL of the host
     * @param clientBuilder the builder for building an OkHttp client, bundled with user configurations
     * @param restBuilder the builder for building an Retrofit client, bundled with user configurations
     */
    public AzureLogAnalyticspublicAPIImpl(String baseUrl, OkHttpClient.Builder clientBuilder, Retrofit.Builder restBuilder) {
        super(baseUrl, clientBuilder, restBuilder);
        initialize();
    }

    /**
     * Initializes an instance of AzureLogAnalyticspublicAPI client.
     *
     * @param restClient the REST client containing pre-configured settings
     */
    public AzureLogAnalyticspublicAPIImpl(RestClient restClient) {
        super(restClient);
        initialize();
    }

    private void initialize() {
        this.querys = new QuerysImpl(retrofit(), this);
    }
}
